apiVersion: apps/v1
kind: Deployment
metadata:
  name: mexc-crypto-futures-bot
  labels:
    app.kubernetes.io/name: mexc-crypto-futures-bot
spec: 
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mexc-crypto-futures-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mexc-crypto-futures-bot
    spec:
      containers:
        - name: mexc-crypto-futures-bot
          image: docker.io/josemariasoladuran/crypto-futures-bot:0.6.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: TELEGRAM_BOT_ENABLED
              value: "true"
            - name: BACKGROUND_TASKS_ENABLED
              value: "true"
            - name: DATABASE_URL
              value: "sqlite+aiosqlite:////app/db/crypto_futures_bot.db"
            - name: ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: mexc-crypto-futures-bot
                  key: root.user
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mexc-crypto-futures-bot
                  key: root.password
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mexc-crypto-futures-bot
                  key: telegram.bot.token
            - name: FUTURES_EXCHANGE
              value: "MEXC"
            - name: FUTURES_EXCHANGE_DEBUG_MODE
              value: "false"
            - name: MEXC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mexc-crypto-futures-bot
                  key: mexc.api.key
            - name: MEXC_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: mexc-crypto-futures-bot
                  key: mexc.api.secret
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  pgrep -f "crypto_futures_bot.main" > /dev/null 2>&1
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  pgrep -f "crypto_futures_bot.main" > /dev/null 2>&1
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/db  # <-- SQLite file will go here
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc